### ISSUE TITLE
invalid file structure in repo

### ISSUE THREAD

**Issue by danmarsden** [wjunkin/moodle-quiz_liveviewgrid#1]
Please fix the structure of the files in this repository - the plugin files should sit in the "root" of this repository - not inside a "liveviewgrid" folder within the repo. Putting it in the root means that people can install your plugin using git submodules subtrees etc.

**Comment by wjunkin** [comment]
Thanks, Dan,
I did not konw the correct structure in github for a sub-mudule. I have submitted a Moodle module but this is my first sub-module. I think this is corrected here now.

**Comment by danmarsden** [comment]
The "histogram" branch looks correct - but the "master" branch still uses the old structure.

Typically most plugin devs will use the "master" branch as the "latest" code and then have various branches for each supported version (if the master branch doesn't support all versions) - If the "Histogram" branch is your latest code you might want to improve the docs and set the default branch in your gihub repo to use "histogram" - although - I would really suggest you use the "master" branch as your latest code as this is what most developers will be expecting.

**Comment by wjunkin** [comment]
Hi, Dan,
I think I have successfully copied the files from the histogram branch into master branch. I will continue to make the other changes that you have suggested (thank you very much) and then carefully check everything out once I have made the changes. I  will do my best to keep the latest corrected code in the master branch.

**Comment by danmarsden** [comment]
looks good to me - nice work! - you might want to close this issue to flag it as being done! :-)
