### ISSUE TITLE
Missing tooltip

### ISSUE THREAD

**Issue by dinism** [wjunkin/moodle-quiz_liveviewgrid#13]
In PT or EN
![imagem](https://user-images.githubusercontent.com/14828021/57193368-25848300-6f32-11e9-92f7-4c3e4ef3fd25.png)

![imagem](https://user-images.githubusercontent.com/14828021/57193392-67adc480-6f32-11e9-91bd-fa018996b94d.png)

**Comment by wjunkin** [comment]
Hi, Dinism,
I think (hope) that the new version has language strings for all the text, including the tooltips. So, I am closing this issue but if you find a tooltip (or any other string) is missing a language string, please let me know.
