### ISSUE TITLE
I'm boring

### ISSUE THREAD

**Issue by dinism** [wjunkin/moodle-quiz_liveviewgrid#17]
Take a look [this video](https://www.escolaagricolavendasnovas.com/images/error2.mp4)
I updated to the last version 1.2.10 (2019053000)
Last commit  ebc4186
The image of question is out of screen and i can't see the histogram and when i inspect the missing i got link: http://localhost/moodle362/mod/quiz/report/liveviewgrid/graph.php?.... as you can see in video
My Moodle is 3.6.4
Sorry about this!

**Comment by dinism** [comment]
The question is this:
![imagem](https://user-images.githubusercontent.com/14828021/58665680-55ecf080-8329-11e9-8a69-f75ef7c28d89.png)

**Comment by wjunkin** [comment]
Hi, Dinis,
You are wonderful to find yet another bug in the Live Report module. It may be necessary for us to communicate about this via direct email. My email address is junkinwf@eckerd.edu.
The important information is the link for the image. You wrote above http://localhost/moodle362/mod/quiz/report/liveviewgrid/graph.php?...
The important information is found in the "..." From the video I was able to see that there are several fr values. I was able to see what seemed to be fr[3]=0.0000&fr[4]=0.00000&total=10&cmid=1099 However, I could not see from the video what came before the fr[3] part of the URL.
If you can send me the complete URL for the image, I may be able to figure out the problem. 
Again, many thanks. (And you are not at all boring!! You are very helpful.)

**Comment by wjunkin** [comment]
Hi, Dinis,
Thanks to your help I found the problem. In removing one bug I introduced another bug. However, I think I have now removed that bug. Hopefully the new version is now free of bugs.
Thanks again. Since I hope that this solves this issue, I am closing this issue. But if you see this or any other problem please let me know.
