### ISSUE TITLE
missing privacy api

### ISSUE THREAD

**Issue by danmarsden** [wjunkin/moodle-quiz_liveviewgrid#2]
Moodle uses a privacy API for GDPR compliance to allow plugins to specify how they deal with user data. Your plugin doesn't appear to store any user data so you can probably implement the null provider class.

Sites that use continuous integration processes will not be able to use your plugin because Moodle runs unit tests which check to see if all extra plugins include the privacy class.

More information on the privacy class is here:
https://docs.moodle.org/dev/Privacy_API

Please note - this issue is not a blocker for approval in the plugins db, but it would be nice to add.

**Comment by wjunkin** [comment]
Thanks, Dan,
I have now added the privacy API for GDPR compliance. You were correct. This sub-module does not store any data, so including the null provider class was pretty easy.

**Comment by danmarsden** [comment]
cool! - you might want to close this to flag that it has been done.
