### ISSUE TITLE
incorrect location and naming for liveview_fraction class

### ISSUE THREAD

**Issue by danmarsden** [wjunkin/moodle-quiz_liveviewgrid#5]
Ideally classes should sit in their own distinct files and should use the frankenstyle prefix

At the very least "liveview_fraction" should be renamed to "quiz_liveviewgrid_fraction" but it would be nice for it to also go into it's own file within the classes folder in your plugin.

**Comment by wjunkin** [comment]
I think I have made the suggested change. The class is now quiz_liveviewgrid_fraction and its code is in the liveviewgrid/classes directory and where it has been called in the report.php code has been modified accordingly.
