### ISSUE TITLE
strange function liveviewshowkey() defined within a function display()

### ISSUE THREAD

**Issue by danmarsden** [wjunkin/moodle-quiz_liveviewgrid#7]
I don't think I've ever seen this before:
https://github.com/wjunkin/moodle-quiz_liveviewgrid/blob/master/liveviewgrid/report.php#L205

It's also not clear why it's even in a function as it is only called once right below.

If it should be in a function I'd recommend moving it into a standalone function in the class instead of embedded within the "display() function. otherwise remove the function completely and just call it in-line.

**Comment by wjunkin** [comment]
Thanks, Dan, for this good suggestion. I think I have made this change. (Now that I am through teaching the physicis course I hope to move forward with this pretty quickly.)
